# Generated by Django 5.0 on 2024-01-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisements", "0003_favoriteadvertisement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="status",
            field=models.TextField(
                choices=[
                    ("OPEN", "Открыто"),
                    ("CLOSED", "Закрыто"),
                    ("DRAFT", "Черновик"),
                ],
                default="OPEN",
            ),
        ),
    ]
