# Generated by Django 5.0 on 2023-12-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_student_group_alter_student_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.CreateModel(
            name="StudTeach",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school",
                        to="school.student",
                    ),
                ),
                (
                    "teachers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school",
                        to="school.teacher",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="teacher",
            field=models.ManyToManyField(
                related_name="students", through="school.StudTeach", to="school.teacher"
            ),
        ),
    ]
