# Generated by Django 5.0 on 2024-01-17 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя датчика")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание датчика"),
                ),
            ],
            options={
                "verbose_name": "датчик",
                "verbose_name_plural": "датчики",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(verbose_name="Температура")),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата измерения"),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="", verbose_name="Фото"),
                ),
                (
                    "sensor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesaurement",
                        to="measurement.sensor",
                        verbose_name="Датчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "измерения",
                "verbose_name_plural": "измерении",
                "ordering": ["sensor_id", "date"],
            },
        ),
    ]
