# Generated by Django 5.0 on 2024-01-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата измерения"
            ),
        ),
    ]
